spring.application.name=device-project
spring.datasource.url=jdbc:postgresql://localhost:5432/device-db
spring.datasource.username=device-user
spring.datasource.password=device-pass

spring.jpa.hibernate.ddl-auto=validate